[package]
name = "patternfly-yew-quickstart"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "A quickstart project for using Patternfly with Yew Stack"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

yew = "0.17"
yew-router = "0.14"

patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }

[patch.'https://github.com/ctron/patternfly-yew']
#patternfly-yew = { path = "../patternfly-yew" }
